export const staticData = [
  {
    title: "Film",
    content: "Listening",
    icon: "film_icon.svg",
    link: "/film",
    type: "film",
  },
  {
    title: "Speak",
    content: "Speaking",
    icon: "speak_icon.svg",
    link: "/speak",
    type: "speak",
  },
  {
    title: "Write",
    content: "Writing",
    icon: "write_icon.svg",
    link: "/write",
    type: "write",
  },
  {
    title: "Interpret",
    content: "Speaking",
    icon: "interpret_icon.svg",
    link: "/interpret",
    type: "interpret",
  },
  {
    title: "Memorize",
    content: "Speaking",
    icon: "memorize_icon.svg",
    link: "/memorize",
    type: "memorize",
  },
  {
    title: "Video class",
    content: "Grammar",
    icon: "video-class_icon.svg",
    link: "/video-class",
    type: "video-class",
  },
  {
    title: "Vocabulary",
    content: "Vocabulary",
    icon: "choose_icon.svg",
    link: "/vocabulary",
    type: "vocabulary",
  },
  {
    title: "Interrogative Form",
    content: "Listening",
    icon: "interrogative-form_icon.svg",
    link: "/interrogative-form",
    type: "interrogative-form",
  },
  {
    title: "Pronouns",
    content: "Pronouns",
    icon: "pronouns_icon.svg",
    link: "/pronouns",
    type: "pronouns",
  },
  {
    title: "Assessment",
    content: "Assessment",
    icon: "assesment_icon.svg",
    link: "/assessment",
    type: "assessment",
  },
];
