import { Inter, Architects_Daughter } from 'next/font/google';
import './css/style.css';
import Header from '@/components/ui/header';
import Banner from '@/components/banner';
import { Wrapper } from '@/components/wrapper';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${architects_daughter.variable} font-inter antialiase tracking-tight`}>
        <Wrapper>
          <Header />
          {children}
          <Banner />
        </Wrapper>
      </body>
    </html>
  );
}
