export const staticData = [
  {
    titleTextID: "unit.film",
    contentTextID: "unit.listening",
    icon: "film_icon.svg",
    link: "/film",
    type: "film",
  },
  {
    titleTextID: "unit.speak",
    contentTextID: "unit.speaking",
    icon: "speak_icon.svg",
    link: "/speak",
    type: "speak",
  },
  {
    titleTextID: "unit.write",
    contentTextID: "unit.writing",
    icon: "write_icon.svg",
    link: "/write",
    type: "write",
  },
  {
    titleTextID: "unit.interpret",
    contentTextID: "unit.speaking",
    icon: "interpret_icon.svg",
    link: "/interpret",
    type: "interpret",
  },
  {
    titleTextID: "unit.memorize",
    contentTextID: "unit.speaking",
    icon: "memorize_icon.svg",
    link: "/memorize",
    type: "memorize",
  },
  {
    titleTextID: "unit.video-class",
    contentTextID: "unit.grammar",
    icon: "video-class_icon.svg",
    link: "/video-class",
    type: "video-class",
  },
  {
    titleTextID: "unit.vocabulary",
    contentTextID: "unit.vocabulary",
    icon: "choose_icon.svg",
    link: "/vocabulary",
    type: "vocabulary",
  },
  {
    titleTextID: "unit.interrogative-form",
    contentTextID: "unit.listening",
    icon: "interrogative-form_icon.svg",
    link: "/interrogative-form",
    type: "interrogative-form",
  },
  {
    titleTextID: "unit.pronouns",
    contentTextID: "unit.pronouns",
    icon: "pronouns_icon.svg",
    link: "/pronouns",
    type: "pronouns",
  },
  {
    titleTextID: "unit.assessment",
    contentTextID: "unit.assessment",
    icon: "assesment_icon.svg",
    link: "/assessment",
    type: "assessment",
  },
];
