name: Demo React App

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /home/ty/open-react-template
          git fetch origin
          git checkout production
          git pull
          pnpm install
          pnpm run build
          pm2 reload react-app
            
          
